# Generated by Django 4.1.6 on 2023-02-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0003_remove_trait_pets"),
        ("pets", "0004_remove_pet_traits_name_pet_trait_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="trait_name",
        ),
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(
                blank=True, related_name="pets", to="traits.trait"
            ),
        ),
    ]
